# Generated by Django 5.1.4 on 2025-03-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='notify',
            field=models.BooleanField(default=True),
        ),
    ]
