services:
  web:
    build: ./videohost
    volumes:
      - ./videohost/:/usr/src/videohost/
      - ./videohost/static/:/usr/src/videohost/static
      - ./videohost/media/:/usr/src/videohost/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
    networks:
      - default

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - "5432:5432"
    networks:
      - default

  redis:
    image: 'redis:alpine'
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - default

  celery:
    build: ./videohost
    command: celery worker --app=core --loglevel=info
    depends_on:
      - web
      - db
      - redis
    restart: on-failure
    volumes:
      - ./videohost/:/usr/src/videohost/
      - ./videohost/media/:/usr/src/videohost/media 
    env_file:
      - ./.env.dev
    networks:
      - default

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./videohost/static:/usr/src/videohost/static
      - ./videohost/media:/usr/src/videohost/media
    ports:
      - "80:80"
    depends_on:
      - web
    
volumes:
  postgres_data: