# Generated by Django 5.1.4 on 2025-01-23 09:18

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=None, upload_to=videos.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.UUIDField(default='107a77bc4d9a4e6a94a514039d2e5b2f', unique=True),
        ),
    ]
