# Generated by Django 5.1.4 on 2025-02-25 15:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
