# Generated by Django 5.1.4 on 2025-01-24 14:16

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_video_alter_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры видео'},
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(upload_to=videos.models.user_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.UUIDField(default='382cfe253a4a4bc3bdcb4412170f340d', unique=True),
        ),
    ]
