# Generated by Django 5.1.4 on 2025-03-24 15:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_watchhistoryitem_alter_watchhistory_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
                ('watch_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.watchhistory')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='videos',
            field=models.ManyToManyField(blank=True, through='videos.WatchHistoryItem', to='videos.video'),
        ),
    ]
