# Generated by Django 5.1.4 on 2025-01-24 14:16

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_genre_options_alter_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(upload_to=videos.models.user_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.UUIDField(default='e7b5ca9316064b5d913b19543668d46f', unique=True),
        ),
    ]
