# Generated by Django 5.1.4 on 2025-02-04 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_like_video_alter_video_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментар', 'verbose_name_plural': 'Коментарі'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанри відео'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'Плейлист', 'verbose_name_plural': 'Плейлисти'},
        ),
        migrations.AlterModelOptions(
            name='saving',
            options={'verbose_name': 'Збереження', 'verbose_name_plural': 'Збереження'},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name': 'Підписка', 'verbose_name_plural': 'Підписки'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Відео', 'verbose_name_plural': 'Відео'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='videos.comment'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='icon',
            field=models.ImageField(upload_to='icons/icons/%Y/%m/%d', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='visibility',
            field=models.CharField(choices=[('Публічний', 'Публічний'), ('Приватний', 'Приватний')], default='Приватний', max_length=15),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.UUIDField(default='e2208fbb220e47f28ab47a316374a857', unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='visibility',
            field=models.CharField(choices=[('Публічний', 'Публічний'), ('Приватний', 'Приватний')], default='Публічний', max_length=15),
        ),
    ]
